#include "init.hpp"

#pragma region Structs
struct CommandLineValuePair {
    wstring name;
    wstring value;
};

wostream& operator<<(wostream& os, const CommandLineValuePair& pair) {
    os << pair.name << "=" << pair.value;
    return os;
}

struct CommandLineArgs {
    wstring programName; // The first argument (the program name)
    wstring programPath; // The full path to the program (can be derived from programName if needed)
    vector<wstring> freeArgs;  // Without any prior dashes (not flags) -> wasd
    vector<wstring> flags;     // With double dashes or / (flags) -> --v, --verbose, --help, /v, /verbose, /help, /?, -?
    vector<CommandLineValuePair> keyValuePairs; // For inline key-value pairs; first is a singular dash, then the value (-filename=name.txt)
};

#pragma endregion

#pragma region Utility Functions
bool vectorContains(const vector<wstring>& vec, const wstring& value) {
    for (const auto& item : vec) {
        if (item == value) {
            return true;
        }
    }
    return false;
}
bool vectorContains(const vector<wstring>& vec, const vector<wstring>& values) {
    for (const auto& value : values) {
        if (vectorContains(vec, value)) {
            return true;
        }
    }
    return false;
}
const wstring lastOfPath(const wstring& path) {
    size_t lastSlashPos = path.find_last_of(L"\\");
    if (lastSlashPos != wstring::npos) {
        return path.substr(lastSlashPos + 1);
    }
    return path;
}
#pragma endregion

#pragma region Command Line Parsing
vector<wstring> GetCommandLineArgs(int& count) {
    LPWSTR* argList = CommandLineToArgvW(GetCommandLineW(), &count);
    vector<wstring> args;
    
    if (argList != nullptr) {
        for (int i = 0; i < count; ++i) {
            args.push_back(wstring(argList[i]));
        }
        LocalFree(argList);
    }
    
    return args;
}

CommandLineArgs ParseCommandLineArgs(const vector<wstring>& args) {
    CommandLineArgs result;
    
    if (!args.empty()) {
        result.programName = lastOfPath(args[0]);
        result.programPath = args[0];
    }

    for (size_t i = 1; i < args.size(); ++i) {
        const auto& arg = args[i];
        if (arg.rfind(L"--", 0) == 0 || arg.rfind(L"/", 0) == 0) {
            result.flags.push_back(arg);
        } else if (arg.rfind(L"-", 0) == 0) {
            size_t equalPos = arg.find(L'=');
            if (equalPos != wstring::npos) {
                CommandLineValuePair pair;
                pair.name = arg.substr(1, equalPos - 1); // Skip the leading dash
                pair.value = arg.substr(equalPos + 1);
                result.keyValuePairs.push_back(pair);
            } else {
                result.flags.push_back(arg);
            }
        } else {
            result.freeArgs.push_back(arg);
        }
    }
    
    return result;
}

void DisplayCommandLineArgs(const CommandLineArgs& args) {
    wcout << L"Free Arguments:" << endl;
    for (const auto& arg : args.freeArgs) {
        wcout << L"  " << arg << endl;
    }
    wcout << L"Flags:" << endl;
    for (const auto& flag : args.flags) {
        wcout << L"  " << flag << endl;
    }

    wcout << L"Key-Value Pairs:" << endl;
    for (const auto& pair : args.keyValuePairs) {
        wcout << L"  " << pair << endl;
    }
}

#pragma endregion

#pragma region User Interaction

void DisplayHelp(const wstring& programName) {
    wcout << L"Usage: " << programName << L" [options] [arguments]" << endl;
    wcout << L"Options:" << endl;
    wcout << L"  --help, -h, -?, /help, /h, /?\t\tDisplay this help message" << endl;
    wcout << L"  -s, --show\t\tDisplay the command line arguments" << endl;
    wcout << L"  -v, --verbose, /verbose\t\tEnable verbose output" << endl;
    wcout << L"  --no-warnings, /no-warnings\t\tDisable warnings" << endl;
    wcout << L"  --show-tokens, /show-tokens, -st, /st\t\tDisplay the tokens generated by the lexer" << endl;
    wcout << L"  --show-ast, /show-ast, -ast, /ast\t\tDisplay the AST generated by the parser" << endl;
    wcout << L"  --no-panic, /no-panic, -np, /np\t\tForbid panicing on errors" << endl;
    wcout << L"  -filename=value, -fn=value\t\tSpecify the input filename (e.g., -filename=name.txt)" << endl;
    wcout << L"  -output=value, -o=value, -outfile=value\t\tSpecify the output filename (e.g., -output=out.txt)" << endl;
}

#pragma endregion

int main(int argc, char* argv[]) {
    int count = 0;
    const vector<wstring> args = GetCommandLineArgs(count);
    CommandLineArgs parsedArgs = ParseCommandLineArgs(args);

    vector<wstring> *freeArgs = &parsedArgs.freeArgs;
    vector<wstring> *flags = &parsedArgs.flags;
    vector<CommandLineValuePair> *keyValuePairs = &parsedArgs.keyValuePairs;

    //DisplayCommandLineArgs(parsedArgs);

    if (vectorContains(*flags, vector<wstring>{L"--show", L"/show", L"-s", L"/s"})) DisplayCommandLineArgs(parsedArgs);

    if (vectorContains(*flags, vector<wstring>{L"--help", L"-h", L"-?", L"/help", L"/h", L"/?"})) {
        DisplayHelp(parsedArgs.programName);
        return 0;
    }

    _verbose = vectorContains(*flags, vector<wstring>{L"-v", L"--verbose", L"/verbose"});
    _showWarnings = !vectorContains(*flags, vector<wstring>{L"--no-warnings", L"/no-warnings", L"-nw", L"/nw"});
    _panic = !vectorContains(*flags, vector<wstring>{L"--no-panic", L"/no-panic", L"-np", L"/np"});

    if (vectorContains(*flags, vector<wstring>{L"--log-globals"})) {
        wcout << L"Global Variables:" << endl;
        wcout << L"_verbose: " << (_verbose ? L"true" : L"false") << endl;
        wcout << L"_showWarnings: " << (_showWarnings ? L"true" : L"false") << endl;
        wcout << L"_panic: " << (_panic ? L"true" : L"false") << endl;
    }

    if (_verbose) wcout << L"Verbose mode enabled." << endl;

    #pragma region Input Filename Extraction
    wstring inputfilename = L"";
    bool inputfilenameProvided = false;
    for (const auto& pair : *keyValuePairs) {
        if (pair.name == L"filename" || pair.name == L"fn") {
            inputfilename = pair.value;
            inputfilenameProvided = true;
            if (_verbose) wcout << L"Got inputfilename from key-value pair: " << inputfilename << endl;
            break;
        }
    }

    if (!inputfilenameProvided) {
        if (freeArgs->size() > 0) {
            inputfilename = (*freeArgs)[0];
            inputfilenameProvided = true;
            freeArgs->erase(freeArgs->begin());  // Remove the first element from the vector
            if (_verbose) wcout << L"Got inputfilename from free arguments: " << inputfilename << endl;
        } else {
            wcout << L"Error: No inputfilename provided." << endl;
            return 1;
        }
    }

    wcout << L"Input filename: " << inputfilename << endl;
    #pragma endregion
    #pragma region Output Filename Extraction
    wstring outputfilename = L"a";
    bool outputfilenameProvided = false;
    for (const auto& pair : *keyValuePairs) {
        if (pair.name == L"output" || pair.name == L"o" || pair.name == L"outfile") {
            outputfilename = pair.value;
            outputfilenameProvided = true;
            if (_verbose) wcout << L"Got outputfilename from key-value pair: " << outputfilename << endl;
            break;
        }
    }
    if (!outputfilenameProvided) {
        if (freeArgs->size() > 0) {
            outputfilename = (*freeArgs)[0];
            outputfilenameProvided = true;
            freeArgs->erase(freeArgs->begin());  // Remove the first element from the vector
            if (_verbose) wcout << L"Got outputfilename from free arguments: " << outputfilename << endl;
        } else {
            if (_verbose) wcout << L"No outputfilename provided, but it's optional so continuing without it." << endl;
        }
    }
    wcout << L"Output filename: " << outputfilename << endl;
    #pragma endregion
    
    #pragma region File Reading
    string narrowInputFilename(inputfilename.begin(), inputfilename.end());
    wifstream inputFile(narrowInputFilename.c_str());
    if (!inputFile.is_open()) {
        wcout << L"Error: Unable to open input file." << endl;
        return 1;
    }
    wstring fileContent((istreambuf_iterator<wchar_t>(inputFile)), istreambuf_iterator<wchar_t>());
    inputFile.close();
    if (_verbose) wcout << L"Read input file content successfully." << endl;
    #pragma endregion

    vector<lexer::Token> tokens = lexer::Tokenize(fileContent);

    if (vectorContains(*flags, vector<wstring>{L"--show-tokens", L"/show-tokens", L"-st", L"/st"})) {
        wcout << L"Tokens:" << endl;
        for (const auto& token : tokens) {
            token.Debug();
        }
    }

    ast::BlockStmt ast = parser::Parse(tokens);
    
    if (vectorContains(*flags, vector<wstring>{L"--show-ast", L"/show-ast", L"-ast", L"/ast"})) {
        wcout << L"\nAST Structure:" << endl;
        ast.Dump();
    }

    return 0;
}