#include "init.hpp"
#include <codecvt>

#pragma region Structs
struct CommandLineValuePair {
    wstring name;
    wstring value;
};

wostream& operator<<(wostream& os, const CommandLineValuePair& pair) {
    os << pair.name << "=" << pair.value;
    return os;
}

struct CommandLineArgs {
    wstring programName; // The first argument (the program name)
    wstring programPath; // The full path to the program (can be derived from programName if needed)
    vector<wstring> freeArgs;  // Without any prior dashes (not flags) -> wasd
    vector<wstring> flags;     // With double dashes or / (flags) -> --v, --verbose, --help, /v, /verbose, /help, /?, -?
    vector<CommandLineValuePair> keyValuePairs; // For inline key-value pairs; first is a singular dash, then the value (-filename=name.txt)
};

#pragma endregion

#pragma region Command Line Parsing
vector<wstring> GetCommandLineArgs(int& count) {
    LPWSTR* argList = CommandLineToArgvW(GetCommandLineW(), &count);
    vector<wstring> args;
    
    if (argList != nullptr) {
        for (int i = 0; i < count; ++i) {
            args.push_back(wstring(argList[i]));
        }
        LocalFree(argList);
    }
    
    return args;
}

CommandLineArgs ParseCommandLineArgs(const vector<wstring>& args) {
    CommandLineArgs result;
    
    if (!args.empty()) {
        result.programName = lastOfPath(args[0]);
        result.programPath = args[0];
    }

    for (size_t i = 1; i < args.size(); ++i) {
        const auto& arg = args[i];
        if (arg.rfind(L"--", 0) == 0 || arg.rfind(L"/", 0) == 0) {
            result.flags.push_back(arg);
        } else if (arg.rfind(L"-", 0) == 0) {
            size_t equalPos = arg.find(L'=');
            if (equalPos != wstring::npos) {
                CommandLineValuePair pair;
                pair.name = arg.substr(1, equalPos - 1); // Skip the leading dash
                pair.value = arg.substr(equalPos + 1);
                result.keyValuePairs.push_back(pair);
            } else {
                result.flags.push_back(arg);
            }
        } else {
            result.freeArgs.push_back(arg);
        }
    }
    
    return result;
}

void DisplayCommandLineArgs(const CommandLineArgs& args) {
    _wcout << L"Free Arguments:" << endl;
    for (const auto& arg : args.freeArgs) {
        _wcout << L"  " << arg << endl;
    }
    _wcout << L"Flags:" << endl;
    for (const auto& flag : args.flags) {
        _wcout << L"  " << flag << endl;
    }

    _wcout << L"Key-Value Pairs:" << endl;
    for (const auto& pair : args.keyValuePairs) {
        _wcout << L"  " << pair << endl;
    }
}

#pragma endregion

#pragma region User Interaction

void DisplayHelp(const wstring& programName) {
    _wcout << L"Usage: " << programName << L" [options] [arguments]" << endl;
    _wcout << L"Options:" << endl;
    _wcout << L"  --help, -h, -?, /help, /h, /?\t\t  Display this help message" << endl;
    _wcout << L"  -s, --show\t\t\t\t  Display the command line arguments" << endl;
    _wcout << L"  -v, --verbose, /verbose\t\t  Enable verbose output" << endl;
    _wcout << L"  --no-warnings, /no-warnings\t\t  Disable warnings" << endl;
    _wcout << L"  --show-tokens, /show-tokens, -st, /st   Display the tokens generated by the lexer" << endl;
    _wcout << L"  --show-ast, /show-ast, -ast, /ast\t  Display the AST generated by the parser" << endl;
    _wcout << L"  --no-panic, /no-panic, -np, /np\t  Forbid panicing on errors" << endl;
    _wcout << L"  --debug, /debug, -d, /d\t\t  Enable debug output" << endl;
    _wcout << L"  --log-globals\t\t\t\t  Log global variables" << endl;
    _wcout << L"  --show, /show, -s, /s\t\t\t  Show the command line arguments (after parsing them)" << endl;
    _wcout << L"  --feedback-mode\t\t\t  Enable feedback mode (creates 'stdout' file, or file with the specified name (-stdout=<filename>))" << endl;
    _wcout << L"  -filename=value, -fn=value\t\t  Specify the input filename (e.g., -filename=\"name.txt\")" << endl;
    _wcout << L"  -output=value, -o=value, -outfile=value Specify the output filename (e.g., -output=\"out.txt\")" << endl;
    _wcout << L"  -ast=value\t\t\t\t  Specify the AST output filename (e.g., -ast=\"ast.txt\")" << endl;
    _wcout << L"  -st=value\t\t\t\t  Specify the symbol table output filename (e.g., -st=\"st.txt\")" << endl;
    _wcout << L"  -stdout=value\t\t\t\t  Specify the STDOUT output filename (e.g., -stdout=\"output.txt\")" << endl;
}

#pragma endregion

int main(int argc, char* argv[]) {
    _setmode(_fileno(stdout), _O_U16TEXT);
    _setmode(_fileno(stdin), _O_U16TEXT);

    int count = 0;
    const vector<wstring> args = GetCommandLineArgs(count);
    CommandLineArgs parsedArgs = ParseCommandLineArgs(args);

    vector<wstring> *freeArgs = &parsedArgs.freeArgs;
    vector<wstring> *flags = &parsedArgs.flags;
    vector<CommandLineValuePair> *keyValuePairs = &parsedArgs.keyValuePairs;

    //DisplayCommandLineArgs(parsedArgs);

    if (vectorContains(*flags, vector<wstring>{L"--show", L"/show", L"-s", L"/s"})) DisplayCommandLineArgs(parsedArgs);

    if (vectorContains(*flags, vector<wstring>{L"--help", L"-h", L"-?", L"/help", L"/h", L"/?"})) {
        DisplayHelp(parsedArgs.programName);
        return 0;
    }

    const bool _feedbackMode = vectorContains(*flags, L"--feedback-mode") ? 1 : 0;

    if (_feedbackMode) _wcout << wstring(20, L'=') << L"[Feedback Mode Enabled]" << wstring(20, L'=') << endl;

    _verbose = _feedbackMode ? true : vectorContains(*flags, vector<wstring>{L"-v", L"--verbose", L"/verbose"});
    _showWarnings =  _feedbackMode ? true : !vectorContains(*flags, vector<wstring>{L"--no-warnings", L"/no-warnings", L"-nw", L"/nw"});
    _panic =  _feedbackMode ? false : !vectorContains(*flags, vector<wstring>{L"--no-panic", L"/no-panic", L"-np", L"/np"});
    _debug = _feedbackMode ? true : vectorContains(*flags, vector<wstring>{L"--debug", L"/debug", L"-d", L"/d"});

    if (vectorContains(*flags, vector<wstring>{L"--log-globals"})) {
        _wcout << L"Global Variables:" << endl;
        _wcout << L"_verbose: " << (_verbose ? L"true" : L"false") << endl;
        _wcout << L"_showWarnings: " << (_showWarnings ? L"true" : L"false") << endl;
        _wcout << L"_panic: " << (_panic ? L"true" : L"false") << endl;
    }

    if (_verbose) _wcout << L"Verbose mode enabled." << endl;

    #pragma region Initialize provided key-value pairs
    wstring inputfilename = L"";
    bool inputfilenameProvided = false;
    wstring outputfilename = L"a";
    bool outputfilenameProvided = false;
    wstring ASToutfilename = L"";
    wstring SToutfilename = L"";
    wstring STDOUTfilename = _feedbackMode ? L"stdout" : L"";
    for (const auto& pair : *keyValuePairs) {
        if (pair.name == L"filename" || pair.name == L"fn") {
            inputfilename = pair.value;
            inputfilenameProvided = true;
            if (_verbose) _wcout << L"Got inputfilename from key-value pair: " << inputfilename << endl;
        } else if (pair.name == L"output" || pair.name == L"o" || pair.name == L"outfile") {
            outputfilename = pair.value;
            outputfilenameProvided = true;
            if (_verbose) _wcout << L"Got outputfilename from key-value pair: " << outputfilename << endl;
        } else if (pair.name == L"ast") {
            ASToutfilename = pair.value;
            if (_verbose) _wcout << L"Got AST output filename from key-value pair: " << ASToutfilename << endl;
        } else if (pair.name == L"st") {
            SToutfilename = pair.value;
            if (_verbose) _wcout << L"Got ST output filename from key-value pair: " << SToutfilename << endl;
        } else if (pair.name == L"stdout") {
            STDOUTfilename = pair.value;
            if (_verbose) _wcout << L"Got STDOUT filename from key-value pair: " << STDOUTfilename << endl;
        }
    }
    #pragma endregion

    wofstream stdoutFile;
    if (!STDOUTfilename.empty()) {  // Reroute _wcout to the specified file
        string narrowSTDOUTfilename(STDOUTfilename.begin(), STDOUTfilename.end());
        stdoutFile.open(narrowSTDOUTfilename.c_str());
        if (stdoutFile.is_open()) {
            stdoutFile.imbue(locale(stdoutFile.getloc(), new codecvt_utf8_utf16<wchar_t>()));
            _wcout.rdbuf(stdoutFile.rdbuf());
            if (_verbose) _wcout << L"Rerouted STDOUT to " << STDOUTfilename << endl;
        } else {
            _wcout << L"Error: Unable to open STDOUT file for writing." << endl;
            return 1;
        };
    }

    #pragma region Input Filename Extraction
    if (!inputfilenameProvided) {
        if (freeArgs->size() > 0) {
            inputfilename = (*freeArgs)[0];
            inputfilenameProvided = true;
            freeArgs->erase(freeArgs->begin());  // Remove the first element from the vector
            if (_verbose) _wcout << L"Got inputfilename from free arguments: " << inputfilename << endl;
        } else {
            _wcout << L"Error: No inputfilename provided." << endl;
            return 1;
        }
    }

    _wcout << L"Input filename: " << inputfilename << endl;
    #pragma endregion
    #pragma region Output Filename Extraction
    if (!outputfilenameProvided) {
        if (freeArgs->size() > 0) {
            outputfilename = (*freeArgs)[0];
            outputfilenameProvided = true;
            freeArgs->erase(freeArgs->begin());  // Remove the first element from the vector
            if (_verbose) _wcout << L"Got outputfilename from free arguments: " << outputfilename << endl;
        } else {
            if (_verbose) _wcout << L"No outputfilename provided, but it's optional so continuing without it." << endl;
        }
    }
    _wcout << L"Output filename: " << outputfilename << endl;
    #pragma endregion
    
    #pragma region File Reading
    string narrowInputFilename(inputfilename.begin(), inputfilename.end());
    ifstream inputFile(narrowInputFilename, ios::binary);
    if (!inputFile.is_open()) {
        _wcout << L"Error: Unable to open input file." << endl;
        return 1;
    }

    stringstream buffer;
    buffer << inputFile.rdbuf();
    string content = buffer.str();
    inputFile.close();

    // Check for and remove UTF-8 BOM (0xEF, 0xBB, 0xBF)
    if (content.size() >= 3 && 
        (unsigned char)content[0] == 0xEF && 
        (unsigned char)content[1] == 0xBB && 
        (unsigned char)content[2] == 0xBF) {
        content.erase(0, 3);
    }

    // Convert UTF-8 bytes to wstring
    wstring fileContent;
    if (!content.empty()) {
        int size_needed = MultiByteToWideChar(CP_UTF8, 0, content.c_str(), (int)content.size(), NULL, 0);
        fileContent.resize(size_needed);
        MultiByteToWideChar(CP_UTF8, 0, content.c_str(), (int)content.size(), &fileContent[0], size_needed);
    }

    if (_verbose) _wcout << L"Read input file content successfully." << endl;
    #pragma endregion

    vector<lexer::Token> tokens = lexer::Tokenize(fileContent);

    if (!SToutfilename.empty()) {
        string narrowSToutFilename(SToutfilename.begin(), SToutfilename.end());
        ofstream stOutFile(narrowSToutFilename.c_str());
        if (stOutFile.is_open()) {
            for (int i = 0; i < tokens.size() - 1; i++) {
                const auto& token = tokens[i];
                wstringstream ss;
                token.Debug(ss);
                stOutFile << wstringToUTF8(ss.str());
                _wcout << L"[ST] Wrote token " << i + 1 << L"/" << tokens.size() << L" to symbol table output file (" + lexer::TokenKindString(token.kind) + L")     \r";
            }
            _wcout << L"[ST] Wrote token " << tokens.size() << L"/" << tokens.size() << L" to symbol table output file.";
            _wcout << L"\n[ST] Writing last token to symbol table output file..." << endl;
            const auto& lastToken = tokens.back();
            wstringstream ss;
            lastToken.Debug(ss, false);
            stOutFile << wstringToUTF8(ss.str());
            stOutFile.close();
            _wcout << L"[ST] Successfully wrote tokens to " << SToutfilename << endl;
        } else {
            _wcout << L"[ST] Error: Unable to open symbol table output file." << endl;
        }
    }

    if (vectorContains(*flags, vector<wstring>{L"--show-tokens", L"/show-tokens", L"-st", L"/st"})) {
        for (const auto& token : tokens) {
            token.Debug();
        }
    }

    if (_feedbackMode) {
        _wcout << L"\n[Feedback Mode] Tokens generated by the lexer:" << endl;
        for (const auto& token : tokens) {
            wstringstream ss;
            token.Debug(ss);
            _wcout << UTF8ToWstring(wstringToUTF8(ss.str()));
        }
        _wcout << L"[Feedback Mode] End of token display." << endl;
    }

    ast::BlockStmt ast = ast::BlockStmt::Null();
    try {
        ast = parser::Parse(tokens);
    } catch (const exception& e) {
        _wcout << L"[AST] Error during parsing: " << e.what() << endl;
        return 1;
    }

    if (!ASToutfilename.empty()) {
        string narrowASToutFilename(ASToutfilename.begin(), ASToutfilename.end());
        ofstream astOutFile(narrowASToutFilename.c_str());
        if (astOutFile.is_open()) {
            _wcout << L"[AST] Writing AST to file..." << endl;
            wstringstream ss;
            ast.Dump(0, ss);
            astOutFile << wstringToUTF8(ss.str());
            astOutFile.close();
            _wcout << L"[AST] Successfully wrote AST to " << ASToutfilename << endl;
        } else {
            _wcout << L"[AST] Error: Unable to open AST output file." << endl;
        }
    }

    if (vectorContains(*flags, vector<wstring>{L"--show-ast", L"/show-ast", L"-ast", L"/ast"})) {
        _wcout << L"\nAST Structure:" << endl;
        ast.Dump();
    }

    if (_feedbackMode) {
        _wcout << L"\n[Feedback Mode] AST generated by the parser:" << endl;
        ast.Dump();
        _wcout << L"[Feedback Mode] End of AST display." << endl;
    }

    if (_feedbackMode) {
        // Write source code to STDOUT for feedback mode
        _wcout << L"\n[Feedback Mode] Source code:" << endl;
        _wcout << fileContent << endl;

        _wcout << L"[Feedback Mode] End of feedback." << endl;
    }

    if (_debug) _wcout << L"Program finished successfully." << endl;
    return 0;
}